import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../constants/questions.dart';
import '../models/visit.dart';
import '../services/api_service.dart';

class LocationFormScreen extends StatefulWidget { final String visitId; final FactoryLocation location; const LocationFormScreen({super.key,required this.visitId,required this.location}); @override State<LocationFormScreen> createState()=>_LocationFormScreenState(); }
class _LocationFormScreenState extends State<LocationFormScreen> with SingleTickerProviderStateMixin{
 late FactoryLocation _loc;late TabController _tabs;final Map<String,String> _answers={};bool _saving=false,_uploading=false;final _picker=ImagePicker();
 @override void initState(){super.initState();_loc=widget.location;_answers.addAll(_loc.answers);_tabs=TabController(length:2,vsync:this);}
 @override void dispose(){_tabs.dispose();super.dispose();}
 Future<void> _save()async{setState(()=>_saving=true);final all=formQuestions.every((q)=>_answers[q.id]?.isNotEmpty==true);_loc.answers=Map<String,String>.from(_answers);_loc.status=all?'concluido':'pendente';try{_loc=await ApiService.updateLocation(widget.visitId,_loc);if(!mounted)return;Navigator.pop(context,_loc);}catch(e){if(mounted)_snack(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_saving=false);}}
 Future<void> _pickPhoto({bool camera=false})async{final img=await _picker.pickImage(source:camera?ImageSource.camera:ImageSource.gallery,imageQuality:85);if(img!=null)await _upload(img.path,'photo');}
 Future<void> _pickDocument()async{final result=await FilePicker.platform.pickFiles(withData:false);if(result?.files.single.path!=null)await _upload(result!.files.single.path!,'document');}
 Future<void> _upload(String path,String type)async{setState(()=>_uploading=true);try{final doc=await ApiService.uploadDocument(widget.visitId,_loc.id,path,type);setState(()=>_loc.documents.add(doc));_snack('Anexo salvo no MongoDB.');}catch(e){_snack(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_uploading=false);}}
 Future<void> _deleteDoc(DocumentItem doc)async{try{await ApiService.deleteDocument(widget.visitId,_loc.id,doc.id);setState(()=>_loc.documents.removeWhere((d)=>d.id==doc.id));}catch(e){_snack(e.toString().replaceFirst('Exception: ',''));}}
 void _snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(_loc.name),bottom:TabBar(controller:_tabs,tabs:const[Tab(icon:Icon(Icons.assignment),text:'Formulário'),Tab(icon:Icon(Icons.attach_file),text:'Anexos')])),body:TabBarView(controller:_tabs,children:[_form(),_attachments()]),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:ElevatedButton(onPressed:_saving||_uploading?null:_save,style:ElevatedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16)),child:_saving?const SizedBox(height:20,width:20,child:CircularProgressIndicator(strokeWidth:2)):const Text('Salvar formulário')))));
 Widget _form()=>ListView(padding:const EdgeInsets.all(16),children:[...formQuestions.asMap().entries.map((entry){final i=entry.key,q=entry.value;return Card(margin:const EdgeInsets.only(bottom:16),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${i+1}. ${q.text}',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),...q.options.map((opt)=>RadioListTile<String>(title:Text(opt),value:opt,groupValue:_answers[q.id],dense:true,contentPadding:EdgeInsets.zero,onChanged:(v){if(v!=null)setState(()=>_answers[q.id]=v);})),])));})]);
 Widget _attachments()=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:8,runSpacing:8,children:[OutlinedButton.icon(onPressed:_uploading?null:()=>_pickPhoto(camera:true),icon:const Icon(Icons.photo_camera),label:const Text('Câmera')),OutlinedButton.icon(onPressed:_uploading?null:()=>_pickPhoto(),icon:const Icon(Icons.photo),label:const Text('Galeria')),OutlinedButton.icon(onPressed:_uploading?null:_pickDocument,icon:const Icon(Icons.upload_file),label:const Text('Documento'))])),if(_uploading)const LinearProgressIndicator(),Expanded(child:_loc.documents.isEmpty?const Center(child:Text('Nenhum anexo adicionado')):ListView.builder(itemCount:_loc.documents.length,itemBuilder:(_,i){final d=_loc.documents[i];return ListTile(leading:Icon(d.type=='photo'?Icons.photo:Icons.description,color:Colors.blue),title:Text(d.name,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(d.type=='photo'?'Foto':'Documento'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>_deleteDoc(d)));}))]);
}
