import 'package:flutter/material.dart';
import '../models/visit.dart';
import '../services/api_service.dart';
import '../widgets/location_card.dart';
import 'location_form_screen.dart';

class VisitDetailScreen extends StatefulWidget { final Visit? visit; const VisitDetailScreen({super.key,this.visit}); @override State<VisitDetailScreen> createState()=>_VisitDetailScreenState(); }
class _VisitDetailScreenState extends State<VisitDetailScreen>{
 late Visit _visit; final _name=TextEditingController(),_address=TextEditingController(),_contact=TextEditingController(); bool _saving=false,_loading=false;
 @override void initState(){super.initState();_visit=widget.visit??Visit(id:'',visitId:0,factoryName:'');_syncControllers();if(_visit.id.isNotEmpty)_load();}
 void _syncControllers(){_name.text=_visit.factoryName;_address.text=_visit.factoryAddress;_contact.text=_visit.factoryContact;}
 Future<void> _load()async{setState(()=>_loading=true);try{_visit=await ApiService.getVisit(_visit.id);_syncControllers();}catch(e){if(mounted)_snack(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_loading=false);}}
 @override void dispose(){_name.dispose();_address.dispose();_contact.dispose();super.dispose();}
 void _snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> _saveVisit()async{if(_name.text.trim().isEmpty){_snack('Informe o nome da fábrica.');return;}setState(()=>_saving=true);_visit.factoryName=_name.text.trim();_visit.factoryAddress=_address.text.trim();_visit.factoryContact=_contact.text.trim();try{final saved=_visit.id.isEmpty?await ApiService.createVisit(_visit):await ApiService.updateVisit(_visit.id,_visit);_visit=saved;_syncControllers();if(mounted)_snack('Visita salva.');setState((){});}catch(e){if(mounted)_snack(e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>_saving=false);}}
 Future<void> _addLocation()async{if(_visit.id.isEmpty){await _saveVisit();if(_visit.id.isEmpty)return;}final name=await _promptLocationName();if(name==null||name.isEmpty)return;try{final loc=await ApiService.addLocation(_visit.id,name);setState(()=>_visit.locations.add(loc));}catch(e){_snack(e.toString().replaceFirst('Exception: ',''));}}
 Future<String?> _promptLocationName({String? initial}){final c=TextEditingController(text:initial??'');return showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:Text(initial==null?'Novo local físico':'Editar local'),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(hintText:'Ex.: Produção, Pátio, Depósito')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(ctx,c.text.trim()),child:Text(initial==null?'Adicionar':'Salvar'))]));}
 Future<void> _editLocation(FactoryLocation loc)async{final name=await _promptLocationName(initial:loc.name);if(name==null||name.isEmpty)return;try{loc.name=name;final updated=await ApiService.updateLocation(_visit.id,loc);setState(()=>_replaceLocation(updated));}catch(e){_snack(e.toString().replaceFirst('Exception: ',''));}}
 void _replaceLocation(FactoryLocation updated){final i=_visit.locations.indexWhere((x)=>x.id==updated.id);if(i>=0)_visit.locations[i]=updated;}
 Future<void> _deleteLocation(FactoryLocation loc)async{final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Excluir local'),content:Text('Deseja excluir "${loc.name}"?'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Excluir'))]));if(ok!=true)return;try{await ApiService.deleteLocation(_visit.id,loc.id);setState(()=>_visit.locations.removeWhere((x)=>x.id==loc.id));}catch(e){_snack(e.toString().replaceFirst('Exception: ',''));}}
 Future<void> _openLocation(FactoryLocation loc)async{final updated=await Navigator.push<FactoryLocation>(context,MaterialPageRoute(builder:(_)=>LocationFormScreen(visitId:_visit.id,location:loc)));if(updated!=null&&mounted){setState(()=>_replaceLocation(updated));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(_visit.id.isEmpty?'Nova visita':'Visita #${_visit.visitId}')),body:_loading?const Center(child:CircularProgressIndicator()):SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
  if(_visit.id.isNotEmpty)_IdField(visitId:_visit.visitId),if(_visit.id.isNotEmpty)const SizedBox(height:16),
  Text('Dados da fábrica',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),
  _field(_name,'Nome da fábrica',Icons.business),const SizedBox(height:12),_field(_address,'Endereço',Icons.location_on),const SizedBox(height:12),_field(_contact,'Contato',Icons.phone),const SizedBox(height:24),
  Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Locais da fábrica',style:Theme.of(context).textTheme.titleMedium),TextButton.icon(onPressed:_addLocation,icon:const Icon(Icons.add),label:const Text('Adicionar'))]),
  if(_visit.locations.isEmpty)const Padding(padding:EdgeInsets.all(16),child:Text('Nenhum local cadastrado. Salve a visita e adicione os locais.',textAlign:TextAlign.center)) else ..._visit.locations.map((loc)=>LocationCard(location:loc,onTap:()=>_openLocation(loc),onEdit:()=>_editLocation(loc),onDelete:()=>_deleteLocation(loc))),
  const SizedBox(height:90),
 ])),bottomNavigationBar:SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:ElevatedButton(onPressed:_saving?null:_saveVisit,style:ElevatedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16)),child:_saving?const SizedBox(height:20,width:20,child:CircularProgressIndicator(strokeWidth:2)):const Text('Salvar visita')))));
 Widget _field(TextEditingController c,String label,IconData icon)=>TextField(controller:c,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),border:const OutlineInputBorder()));
}
class _IdField extends StatelessWidget{final int visitId;const _IdField({required this.visitId});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.blue.shade50,borderRadius:BorderRadius.circular(12),border:Border.all(color:Colors.blue.shade200)),child:Row(children:[const Icon(Icons.badge,color:Colors.blue),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ID da visita (gerado pelo banco)',style:TextStyle(fontSize:12)),Text('#$visitId',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))])]));}
